//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.12.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "bentoConfigurationStepsComposition"
	/// <summary>Bento Configuration Steps Composition</summary>
	public partial interface IBentoConfigurationStepsComposition : IPublishedElement
	{
		/// <summary>Configuration Steps</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ConfigurationStepBlock> ConfigurationSteps { get; }

		/// <summary>Finish Step Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string FinishStepText { get; }

		/// <summary>Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string Heading { get; }

		/// <summary>Sub Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string SubHeading { get; }
	}

	/// <summary>Bento Configuration Steps Composition</summary>
	[PublishedModel("bentoConfigurationStepsComposition")]
	public partial class BentoConfigurationStepsComposition : PublishedElementModel, IBentoConfigurationStepsComposition
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const string ModelTypeAlias = "bentoConfigurationStepsComposition";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BentoConfigurationStepsComposition, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public BentoConfigurationStepsComposition(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Configuration Steps
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("configurationSteps")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ConfigurationStepBlock> ConfigurationSteps => GetConfigurationSteps(this);

		/// <summary>Static getter for Configuration Steps</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ConfigurationStepBlock> GetConfigurationSteps(IBentoConfigurationStepsComposition that) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ConfigurationStepBlock>>("configurationSteps");

		///<summary>
		/// Finish Step Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("finishStepText")]
		public string FinishStepText => GetFinishStepText(this);

		/// <summary>Static getter for Finish Step Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetFinishStepText(IBentoConfigurationStepsComposition that) => that.Value<string>("finishStepText");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("heading")]
		public string Heading => GetHeading(this);

		/// <summary>Static getter for Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetHeading(IBentoConfigurationStepsComposition that) => that.Value<string>("heading");

		///<summary>
		/// Sub Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subHeading")]
		public string SubHeading => GetSubHeading(this);

		/// <summary>Static getter for Sub Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetSubHeading(IBentoConfigurationStepsComposition that) => that.Value<string>("subHeading");
	}
}
